(()=>{
const content=window.CASO_CONTENT,CASES=content.cases,KEY='prisma-progress-v6';
const emptyState=()=>({route:'home',caseId:null,current:null,answers:{},attempts:{},recent:[],session:null,lastSessions:{}});
let S=(()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&typeof x==='object'?Object.assign(emptyState(),x):emptyState()}catch{return emptyState()}})();
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=x=>String(x||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[₀₁₂₃₄₅₆₇₈₉]/g,c=>'₀₁₂₃₄₅₆₇₈₉'.indexOf(c)).replace(/[⁰¹²³⁴⁵⁶⁷⁸⁹]/g,c=>'⁰¹²³⁴⁵⁶⁷⁸⁹'.indexOf(c)).replace(/\s+/g,'').replace(/·/g,'');
const all=()=>CASES.flatMap(c=>c.activities.map(a=>({a,c})));
function mastery(skill){const x=all().filter(z=>z.a.skill===skill&&S.attempts[z.a.id]);return x.length?Math.round(x.reduce((n,z)=>n+(S.attempts[z.a.id].correct?1:0),0)/x.length*100):0}
function resetProgress(){if(!confirm('¿Quieres borrar todo el avance y empezar de nuevo? Se eliminarán respuestas, intentos y progreso guardado en este navegador.'))return;S=emptyState();localStorage.removeItem(KEY);home()}
function valencePanel(){return `<div class="valencepanel"><div class="valencehead"><div><small>HERRAMIENTA</small><strong>Consultar valencias</strong></div><button type="button" onclick="closeValences()">×</button></div><p>Primero intenta recordarlas. Si no las recuerdas, introduce el símbolo del elemento.</p><div class="valenceform"><input id="valenceSymbol" maxlength="2" autocomplete="off" spellcheck="false" placeholder="Fe"><button type="button" onclick="lookupValence()">Consultar</button></div><div id="valenceResult"></div></div>`}
function openValences(){if(document.querySelector('.valencepanel'))return;const b=document.querySelector('.valencebutton');if(b){b.insertAdjacentHTML('afterend',valencePanel());document.querySelector('#valenceSymbol')?.focus()}}
function closeValences(){document.querySelector('.valencepanel')?.remove()}
function lookupValence(){const el=document.querySelector('#valenceSymbol'),out=document.querySelector('#valenceResult');if(!el||!out)return;const raw=el.value.trim();const key=raw?raw[0].toUpperCase()+raw.slice(1).toLowerCase():'';const d=window.PRISMA_VALENCES?.[key];out.innerHTML=d?`<div class="valenceok"><strong>${esc(d.name)} (${key})</strong><span>Valencias habituales: <b>${esc(d.v)}</b></span></div>`:`<div class="valenceno">No encuentro ese elemento. Introduce su símbolo químico, por ejemplo <b>Fe</b>, <b>Na</b>, <b>Cl</b> o <b>S</b>.</div>`;el.focus()}
function header(active='home'){return `<header><div class="brand"><b>P</b><strong>PRISMA</strong></div><nav><button class="${active==='home'?'on':''}" onclick="go('home')">Alumno</button><button class="${active==='design'?'on':''}" onclick="go('design')">Diseño</button><button class="resetbtn" onclick="resetProgress()">Reiniciar avance</button></nav></header>`}
function home(){document.querySelector('#app').innerHTML=header()+`<main><section class="hero"><small>PRISMA · APRENDIZAJE</small><h1>Un lugar para entender,<br>no solo para responder.</h1><p>Explora problemas, conecta ideas y vuelve sobre lo que todavía necesita práctica.</p></section><section class="subjects"><article class="subject active" onclick="go('module')"><i>Q</i><small>ACTIVO</small><h2>Química</h2><p>Materia, formulación, nomenclatura y transformaciones.</p><strong>Entrar →</strong></article><article class="subject locked"><span class="lock">⌁</span><small>EN CONSTRUCCIÓN</small><h2>Física</h2><p>Modelos, magnitudes, relaciones y problemas.</p><em>Próximamente</em></article><article class="subject locked"><span class="lock">⌁</span><small>EN CONSTRUCCIÓN</small><h2>Matemáticas</h2><p>Razonamiento, funciones, álgebra y resolución de problemas.</p><em>Próximamente</em></article></section><section class="banner"><div><small>QUÍMICA · MÓDULO ACTIVO</small><h2>${content.module.title}</h2><p>${content.module.subtitle}</p></div><button onclick="go('module')">Continuar →</button></section></main>`}
function modulePage(){document.querySelector('#app').innerHTML=header()+`<main><button class="back" onclick="go('home')">← PRISMA</button><section class="hero compact"><small>QUÍMICA</small><h1>${content.module.title}</h1><p>${content.module.subtitle}</p></section><section class="cases">${CASES.map(c=>{const ls=S.lastSessions[c.id];return `<article onclick="enter('${c.id}')"><small>CASO ${c.number}</small><h2>${c.title}</h2><footer><span>${ls?`Último intento: ${ls.answered}/${c.activities.length} · ${ls.correct} aciertos`: 'Sin intento anterior'}</span><b>Entrar →</b></footer></article>`}).join('')}</section><div class="module-tools"><button onclick="resetProgress()">Reiniciar todo el avance</button></div></main>`}
function pick(c){const seen=S.session&&S.session.caseId===c.id?S.session.seen:[];let pool=c.activities.filter(a=>!seen.includes(a.id)&&!S.recent.includes(a.id));if(!pool.length)pool=c.activities.filter(a=>!seen.includes(a.id));if(!pool.length)return null;pool=pool.map(a=>({a,score:(a.type==='input_formula'||a.type==='input_name'?40:0)+100-mastery(a.skill)+Math.random()*35})).sort((x,y)=>y.score-x.score);return pool[0].a}
function enter(id){const c=CASES.find(x=>x.id===id)||CASES[0];S.caseId=c.id;S.current=null;S.route='case';S.session={caseId:c.id,seen:[],position:1,answered:0,correct:0,id:Math.random().toString(36).slice(2)};save();casePage()}
function normName(x){return norm(x).replace(/[()\[\]{}.,;:]/g,'').replace(/\b(i|ii|iii|iv|v|vi|vii|viii|ix|x)\b/g,'$1')}
function evaluate(a,v){if(a.type==='choice')return Number(v)===a.correct;const x=a.type==='input_name'?normName(v):norm(v);return [...(a.answers||[]),...(a.aliases||[])].some(ans=>(a.type==='input_name'?normName(ans):norm(ans))===x)}
function nameVariants(a){return a.displayNames&&a.displayNames.length?a.displayNames:[...(a.answers||[]),...(a.aliases||[])].slice(0,2)}
function namesMarkup(a){return nameVariants(a).map((n,i)=>`<div class="namevariant"><span>${i===0?'Nombre 1':'Nombre 2'}</span>${formatChem(n)}</div>`).join('')}
function correctDisplay(a){if(a.type==='input_name')return nameVariants(a).join(' / ');if(a.type==='choice')return a.options[a.correct];return a.answers[0]}
function extractFormulaParts(v){const x=String(v||'').replace(/[₀₁₂₃₄₅₆₇₈₉]/g,c=>'₀₁₂₃₄₅₆₇₈₉'.indexOf(c));const parts={};for(const m of x.matchAll(/([A-Z][a-z]?)(\d*)/g))parts[m[1]]=(parts[m[1]]||0)+Number(m[2]||1);return parts}
function oxidationState(text){const m=String(text||'').match(/\(([IVXLCDM]+)\)/i);return m?m[1].toUpperCase():null}
function errorAnalysis(a,v,correct){
 if(a.type==='choice')return 'Compara la opción que elegiste con la explicación de la solución y localiza qué idea has interpretado de otra manera.';
 if(a.type==='input_formula'){
  if(!String(v).trim())return 'No has escrito una fórmula. Antes de continuar, intenta reconstruirla paso a paso.';
  if(/[A-Z][a-z]?\(/.test(correct)&&!String(v).includes('('))return 'La sustancia contiene un grupo que debe aparecer unido. Revisa si necesitas paréntesis.';
  const u=extractFormulaParts(v),e=extractFormulaParts(correct),ue=Object.keys(u),ee=Object.keys(e);
  if(ue.some(k=>!ee.includes(k))||ee.some(k=>!ue.includes(k)))return 'Parece que el error está en los elementos que aparecen en la fórmula: comprueba qué especies intervienen.';
  if(ue.some(k=>u[k]!==e[k]))return 'Los elementos son los adecuados, pero cambia alguna cantidad: revisa los subíndices y la proporción entre ellos.';
  return 'La fórmula no coincide. Compara elemento por elemento, subíndice por subíndice y comprueba la proporción de la fórmula.';
 }
 const u=String(v||'').toLowerCase(),e=String(correct||'').toLowerCase();
 if(oxidationState(v)!==oxidationState(correct)&&oxidationState(correct))return 'Los elementos y la familia parecen cercanos, pero revisa el número de oxidación indicado entre paréntesis.';
 const families=['oxido','hidroxido','hidruro','peroxido','cloruro','bromuro','yoduro','fluoruro','sulfuro','nitruro','nitrato','nitrito','sulfato','sulfito','carbonato','hidrogenocarbonato','hipoclorito','clorato','perclorato','fosfato','acido'];
 const ufam=families.find(f=>norm(u).includes(f)),efam=families.find(f=>norm(e).includes(f));
 if(ufam!==efam)return 'Revisa la familia del compuesto: el tipo de sustancia que has nombrado no coincide con el de la solución.';
 return 'Compara primero los elementos y después la familia del compuesto. Si es necesario, revisa también el número de oxidación.';
}
function casePage(){
 const c=CASES.find(x=>x.id===S.caseId)||CASES[0];
 if(!S.session||S.session.caseId!==c.id)S.session={caseId:c.id,seen:[],position:1,answered:0,correct:0,id:Math.random().toString(36).slice(2)};
 let a=c.activities.find(x=>x.id===S.current);if(!a){a=pick(c);if(!a){finishCase();return}S.current=a.id;save()}
 const stored=S.attempts[a.id],t=stored&&stored.sessionId===S.session.id?stored:null;
 const input=a.type==='choice'?`<div class="opts">${a.options.map((o,i)=>`<label><input type="radio" name="ans" value="${i}"><span>${esc(o)}</span></label>`).join('')}</div>`:`<input class="answerline" id="answer" autocomplete="off" spellcheck="false" placeholder="Escribe aquí…">`;
 const post=t&&!t.correct?`<div class="errorreview"><small>ANALIZA EL ERROR</small><p>${esc(t.analysis)}</p><div class="compare"><div><small>TU RESPUESTA</small><div>${formatChem(t.value)}</div></div><div><small>RESPUESTAS VÁLIDAS</small>${a.type==='input_name'?`<div class="namevariants">${namesMarkup(a)}</div>`:`<div>${formatChem(t.correctAnswer)}</div>`}</div></div><p class="reflection">Antes de continuar, intenta explicar mentalmente qué regla o paso te llevó a tu respuesta.</p></div>`:'';
 const pos=S.session.position,total=c.activities.length;
 document.querySelector('#app').innerHTML=header()+`<main class="narrow"><div class="casebar"><button class="back" onclick="leaveCase()">← Formulación inorgánica</button><span>PREGUNTA ${pos} DE ${total}</span></div><div class="progressline"><span style="width:${Math.round(pos/total*100)}%"></span></div><section class="caseintro"><small>CASO ${c.number}</small><h1>${c.title}</h1></section><section class="q"><small>${esc(a.skill)}</small><h2>${esc(a.title)}</h2><div class="prompt">${formatChem(a.prompt)}</div><button class="valencebutton" type="button" onclick="openValences()">⌄ Consultar valencias de un elemento</button>${t?`<div class="feedback ${t.correct?'ok':'bad'}"><b>${t.correct?'Correcto.':'Hay algo que revisar.'}</b><p>${esc(t.feedback)}</p>${a.type==='input_name'?`<div class="correct-answer"><small>2 NOMENCLATURAS VÁLIDAS</small><div class="namevariants">${namesMarkup(a)}</div></div>`:(!t.correct?`<div class="correct-answer"><small>RESPUESTA CORRECTA</small><div>${formatChem(t.correctAnswer)}</div></div>`:'')}</div>${post}`:input}${!t&&a.type!=='choice'?`<p class="formatnote">Puedes escribir los subíndices como números normales. Por ejemplo: <b>Fe2O3</b>.</p>`:''}<div class="actions">${t?`<button onclick="next()">${pos>=total?(t.correct?'Terminar caso →':'He revisado el error y terminar →'):(t.correct?'Otra pregunta →':'He revisado el error →')}</button>`:`<button onclick="answer()">Comprobar</button>`}</div></section></main>`;
}
function formatChem(x){return esc(x).replace(/([A-Za-z\)])([₀₁₂₃₄₅₆₇₈₉]+)/g,'$1<sub>$2</sub>').replace(/([A-Za-z\)])([0-9]+)/g,'$1<sub>$2</sub>')}
function answer(){const c=CASES.find(x=>x.id===S.caseId);if(!c||!S.current)return;const a=c.activities.find(x=>x.id===S.current);if(!a)return;const v=a.type==='choice'?document.querySelector('input[name=ans]:checked')?.value:document.querySelector('#answer')?.value.trim();if(v==null||v==='')return alert('Responde primero.');const ok=evaluate(a,v),correctAnswer=correctDisplay(a);const fb=ok?a.feedback:(a.type==='input_formula'?'Compara la fórmula que has escrito con la solución y busca el punto exacto en el que cambia.':'Compara tu nombre con las dos nomenclaturas válidas y localiza qué parte de tu respuesta no coincide con ninguna de ellas.');S.answers[a.id]=v;S.attempts[a.id]={correct:ok,feedback:fb,value:v,correctAnswer,analysis:errorAnalysis(a,v,correctAnswer),sessionId:S.session.id};S.session.answered=(S.session.answered||0)+1;if(ok)S.session.correct=(S.session.correct||0)+1;save();casePage()}
function next(){const c=CASES.find(x=>x.id===S.caseId);if(!c||!S.current)return;const pos=S.session.position,total=c.activities.length;if(pos>=total){finishCase();return}S.session.seen.push(S.current);S.recent=[...S.recent.filter(x=>x!==S.current),S.current].slice(-8);S.current=null;S.session.position=pos+1;save();casePage()}
function finishCase(){const c=CASES.find(x=>x.id===S.caseId);if(c&&S.session)S.lastSessions[c.id]={answered:S.session.answered||0,correct:S.session.correct||0,completed:true};S.current=null;S.session=null;S.route='module';save();alert(`Has completado el CASO ${c.number}: ${c.activities.length} preguntas.`);modulePage()}
function leaveCase(){const c=CASES.find(x=>x.id===S.caseId);if(c&&S.session)S.lastSessions[c.id]={answered:S.session.answered||0,correct:S.session.correct||0,completed:false};S.current=null;S.session=null;S.route='module';save();modulePage()}
function design(){document.querySelector('#app').innerHTML=header('design')+`<main><section class="hero compact"><small>PRISMA · DISEÑO</small><h1>Construcción del producto</h1><p>Espacio para modificar contenidos, estructura y metodología. No es una zona de supervisión.</p></section><section class="designgrid"><article><small>QUÍMICA</small><h2>Formulación inorgánica</h2><p>${CASES.length} CASOS · ${CASES.reduce((n,c)=>n+c.activities.length,0)} actividades.</p></article><article><small>ADAPTACIÓN</small><h2>Pool de preguntas</h2><p>Al volver a entrar cambian las preguntas y se priorizan habilidades menos consolidadas.</p></article></section><article class="designpanel"><small>CASOS ACTUALES</small>${CASES.map(c=>`<div class="row"><span><b>CASO ${c.number}</b> · ${c.title}</span><em>${c.activities.length} preguntas</em></div>`).join('')}</article></main>`}
function go(r){S.route=r;save();r==='home'?home():r==='module'?modulePage():r==='design'?design():casePage()}
window.go=go;window.enter=enter;window.answer=answer;window.next=next;window.resetProgress=resetProgress;window.leaveCase=leaveCase;window.openValences=openValences;window.closeValences=closeValences;window.lookupValence=lookupValence;home();
})();
